Add optional argument to override Histogram's buckets.
Closes https://github.com/http4s/http4s/issues/2423

Note that I chose NonEmptyList[Double] instead of List[Double] due to:

```scala
$amm
Loading...
Welcome to the Ammonite Repl 1.0.3
(Scala 2.12.4 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`io.prometheus:simpleclient:0.5.0`
import $ivy.$

@ import io.prometheus.client.{Histogram, CollectorRegistry}
import io.prometheus.client.{Histogram, CollectorRegistry}

@ val c2 = new CollectorRegistry()
c2: CollectorRegistry = io.prometheus.client.CollectorRegistry@351d93bd

@ Histogram.build().buckets(List.empty[Double] : _*).name("foo").help("help").labelNames("bar").register(c2)
java.lang.IllegalStateException: Histogram must have at least one bucket.
```