Narrow implicits to avoid 2.11.12 compile-time error.
```scala
[error] /home/travis/build/http4s/http4s/core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala:85:69: type mismatch;
[error]  found   : Either[NumberFormatException,Int]
[error]  required: ?{def toOption: ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method EitherSyntax in package http4s of type [L, R](self: Either[L,R])org.http4s.package.EitherSyntax[L,R]
[error]  and method catsSyntaxEither in trait EitherSyntax of type [A, B](eab: Either[A,B])cats.syntax.EitherOps[A,B]
[error]  are possible conversion functions from Either[NumberFormatException,Int] to ?{def toOption: ?}
[error]       val int: Option[Int] = Either.catchOnly[NumberFormatException](s.toInt).toOption
[error]                                                                     ^
[error] one error found
[error] (core / Compile / compileIncremental) Compilation failed
[error] Total time: 67 s, completed Jul 2, 2019 2:27:51 PM
```